In [2]:
#integer array
import numpy as np
np.array([1,2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
#to explicitly set the data type
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
#nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [1, 3, 5]])

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])