In [5]:
#Specifying output
import numpy as np
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
print(y)

[ 0. 10. 20. 30. 40.]


In [6]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [7]:
#Aggregates
#Calling reduce on the add ufunc returns the sum of all elements in the array
x = np.arange(1, 6)
np.add.reduce(x)

15

In [8]:
np.multiply.reduce(x)

120

In [9]:
#to store all the intermediate results of the computation
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [10]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [11]:
#compute the output of all pairs of two different inputs using
#the outer method
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])