In [28]:
import numpy as np
rng = np.random.RandomState(0)
x = rng.randint(10, size = (3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [29]:
#values less than 6
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [30]:
#counting values less than 6
np.count_nonzero(x<6)

8

In [31]:
#another way
np.sum(x<6)

8

In [33]:
#values less than 6 in each row
np.sum(x<6, axis = 1)

array([4, 2, 2])

In [34]:
#are there any values greater than 8?
np.any(x>8)

True

In [35]:
#are there any values less than zero?
np.any(x<0)

False

In [36]:
#are all the values less than 10?
np.all(x<10)

True

In [38]:
#are all values equal to 6?
np.all(x == 6)

False

In [39]:
#are all values in each row less than 8?
np.all(x<8, axis = 1)

array([ True, False,  True])

# Boolean arrays as Masks

In [40]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [41]:
#to select
x[x<5]

array([0, 3, 3, 3, 2, 4])