# Exploring Fancy Indexing

In [16]:
import numpy as np
rand = np.random.RandomState(42) #seeding to get same random numbers
x = rand.randint(100, size = 10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [17]:
#to access three different elements
ind = [2, 4, 6] #index of numbers that you want to select
x[ind]

array([14, 60, 82])

In [23]:
ind = np.array([[3, 7], [4,5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [24]:
#for multiple dimensions
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
row = np.array([0, 1, 2])
column = np.array([1, 2, 3])
a[row, column]
#works like a[0, 1], a[1, 2], a[2, 3]

array([ 1,  6, 11])

In [35]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [34]:
a[row[:, np.newaxis], column]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [37]:
#Combining fancy indexing with simple indexing
a[2, [2, 0, 1]]

array([10,  8,  9])

In [39]:
#Combining fancy indexing with slicing
a[1:, [3, 0, 1]]

array([[ 7,  4,  5],
       [11,  8,  9]])

In [42]:
#Combining fancy indexing with masking
mask = np.array([1, 0, 1, 0], dtype = bool)
a[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

# Modifying values with fancy indexing

In [44]:
y = np.zeros(10)
y[[0, 0]] = [4, 6]
y#x[0] = 4 then, x[0] = 6

array([6., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
y[0:]

array([6., 0., 0., 0., 0., 0., 0., 0., 0., 0.])