In [3]:
import numpy as np
x = np.array([5, 3, 2, 1, 4])
np.sort(x)

array([1, 2, 3, 4, 5])

In [4]:
x

array([5, 3, 2, 1, 4])

In [6]:
#to sort the array in-place,
x.sort()
x

array([1, 2, 3, 4, 5])

In [13]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)#returns the indices of the sorted elements
print(i)

[1 0 3 2 4]


# Sorting along rows or columns

In [8]:
import numpy as np
rand = np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))#randint(low, high, size)
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [9]:
np.sort(x, axis = 0) #sort each column of x

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [10]:
np.sort(x, axis = 1)#sort each row of x

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Partial Sorts: Partitioning

np.partition takes an array and a number K; the result is a new array with the smallest
K values to the left of the partition, and the remaining values to the right, in arbitrary
order

In [6]:
import numpy as np
X = np.array([1, 6, 4, 5, 2, 3, 0])
np.partition(X, 3)

array([0, 1, 2, 3, 4, 6, 5])

In [11]:
#for multidimensional array
np.partition(x, 2, axis=1)#row

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

In [13]:
np.partition(x, 2, axis=0)#column

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])