In [6]:
#Creating a length-10 integer array filled with zeros
import numpy as np
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
#Creating a 3 X 5 floating-point array filled with 1s
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#Creating a 3 X 5 array filled with 3
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
#one dimensional array of even numbers till 20
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
#array of five numbers evenly seperated between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
#3X3 array of randomly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.82576986, 0.54516695, 0.91624978],
       [0.25571346, 0.23037601, 0.87913688],
       [0.39259103, 0.27951255, 0.72340179]])

In [21]:
#3x3 array of normally distributed random values with mean 0 and standaard 
#deviation 1
np.random.normal(0, 1, (3,3))

array([[-0.20062703, -1.00008646, -0.22236663],
       [-0.00216834,  0.57546344,  0.48585508],
       [ 1.74765794,  1.03749916, -0.84330402]])

In [22]:
#3x3 random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 6, 6],
       [3, 5, 0],
       [7, 1, 5]])

In [23]:
#3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# uninitialized array of three integers 
# The values will be whatever happensto already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])