In [6]:
#x[start: stop: step]
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[:5]#first five

array([0, 1, 2, 3, 4])

In [9]:
x[5:]#elements after index 5, includes 5th index

array([5, 6, 7, 8, 9])

In [10]:
x[4:7]#elements from 4th to 7th index, excluding 7th position

array([4, 5, 6])

In [11]:
x[::2]#every other element, stepping 2

array([0, 2, 4, 6, 8])

In [12]:
x[1::2]#every other element starting from first position

array([1, 3, 5, 7, 9])

In [14]:
x[::-1]#all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [15]:
x[5::-2]#reversed every other element from index 5

array([5, 3, 1])