In [2]:
import numpy as np
x = np.random.randint(10, size = (3, 4))
x

array([[8, 3, 5, 1],
       [3, 4, 7, 0],
       [6, 0, 0, 4]])

In [3]:
#two rows, three columns
x[:2, :3]

array([[8, 3, 5],
       [3, 4, 7]])

In [12]:
x[:3, ::2]#three rows, every other column

array([[5, 0],
       [2, 0],
       [4, 9]])

In [13]:
x[::-1, ::-1]#subarray reversed

array([[0, 9, 2, 4],
       [1, 0, 8, 2],
       [4, 0, 1, 5]])

In [4]:
#accessing array rows and columns
x[:, 0] #first column

array([7, 7, 2])

In [5]:
x[0, :]#first row

array([7, 0, 8, 4])

In [6]:
x[0]#first row

array([7, 0, 8, 4])

In [9]:
#creating copies of array
x2 = x[:2, :2].copy()
x2

array([[7, 0],
       [7, 1]])