In [2]:
import numpy as np
grid = np.arange(1, 10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#conversion of 1D array into 2D row or column matrix
x = np.array([1, 2, 3])
x.reshape(1, 3)

array([[1, 2, 3]])

In [6]:
x.reshape(3, 1)#three rows one column

array([[1],
       [2],
       [3]])

In [7]:
#same thing with newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [8]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [4]:
x.reshape(-1, 1)

array([[1],
       [2],
       [3]])