In [14]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([1, 1, 1])
a = np.concatenate([x, y, z])
a

array([1, 2, 3, 3, 2, 1, 1, 1, 1])

In [6]:
#concatenating two dimensional arrays
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
#concatenate along the second axis
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [8]:
# *It's clear to use np.vstack and np.hstack to work with
# *mixed dimensional arrays

np.vstack([x, grid])


array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
np.vstack([grid, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [11]:
y = np.array([[33],
               [44]])
np.hstack([y, grid])

array([[33,  1,  2,  3],
       [44,  4,  5,  6]])

In [12]:
##################################################
# *Splitting of arrays

In [15]:
a

array([1, 2, 3, 3, 2, 1, 1, 1, 1])

In [20]:
s1, s2, s3 = np.split(a, [3, 6])
print(s1, s2, s3)

[1 2 3] [3 2 1] [1 1 1]


In [22]:
grid = np.arange(16).reshape(4, 4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [28]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
